# Generated by Django 2.2.2 on 2019-12-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='col',
            name='uname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appone.Uni'),
            preserve_default=False,
        ),
    ]
