# Generated by Django 2.2.2 on 2020-02-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=10)),
                ('eaddress', models.CharField(max_length=20)),
                ('esalary', models.FloatField()),
                ('experience', models.FloatField()),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=2)),
            ],
        ),
    ]
