# Generated by Django 2.2.2 on 2020-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200223_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
