# Generated by Django 2.2.2 on 2020-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
