# Generated by Django 2.2.2 on 2020-01-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='test',
            new_name='teast',
        ),
    ]
