# Generated by Django 2.2.2 on 2020-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200115_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='color',
            field=models.CharField(default='brown', max_length=50),
            preserve_default=False,
        ),
    ]
